FROM amazon/aws-lambda-python:3.12

# install chrome dependencies
RUN dnf install -y atk cups-libs gtk3 libXcomposite alsa-lib \
    libXcursor libXdamage libXext libXi libXrandr libXScrnSaver \
    libXtst pango at-spi2-atk libXt xorg-x11-server-Xvfb \
    xorg-x11-xauth dbus-glib dbus-glib-devel nss mesa-libgbm jq unzip

COPY . /app

RUN chmod +x /app/scraper_lambda/chrome-installer.sh
RUN /app/scraper_lambda/chrome-installer.sh
RUN #rm ./chrome-installer.sh

RUN pip install -r /app/requirements.txt
# working directory is /app
WORKDIR /app

CMD [ "scraper_lambda.selenium_script.lambda_handler" ]