version: '3'
services:
  app:
    build:
      context: .
    volumes:
      - ./:/app
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    env_file:
      - ./.env.prod
  redis:
    image: redis:alpine
  celery:
    build:
      context: .
    command: celery -A finance.celery_app worker -l info --concurrency=4
    volumes:
      - ./:/app
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - app
  celery-beat:
    build:
      context: .
    command: celery -A finance.celery_app beat -l info
    volumes:
      - ./:/app
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - app
  test:
    build:
      context: .
    volumes:
      - ./:/app
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    command: python manage.py test --verbosity=3
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - app
      - celery
      - celery-beat
