version: '3'
# https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/ for referance
# static files are not taken care of in this project.
# new user for applications is not taken care of in this project
# media files are also not taken care of
services:
  app:
    build:
      context: .
    expose:
      - "8000"
    volumes:
      - ./:/app
      - static_volume:/app/staticfiles
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
    command: >
      sh -c "python3 manage.py wait_for_db &&
             gunicorn finance.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - ./.env.prod
  redis:
    image: redis:alpine
  celery:
    restart: always
    build:
      context: .
    command: celery -A finance.celery_app worker -l info
    volumes:
      - ./:/app
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - app
  celery-beat:
    build:
      context: .
    command: celery -A finance.celery_app beat -l debug
    volumes:
      - ./:/app
      - $HOME/.aws/credentials:/app/.aws/credentials:ro
    env_file:
      - ./.env.prod
    depends_on:
      - redis
      - app
  nginx:
    build: ./nginx
    ports:
      - 8000:80
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - app

volumes:
  static_volume:


