# Generated by Django 2.2.7 on 2020-02-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tag',
            field=models.CharField(choices=[('cloths', 'cloths'), ('coffie', 'coffie'), ('same', 'same'), ('other', 'other'), ('outings', 'outings'), ('supermarcket', 'supermarcket'), ('transportation', 'transportation'), ('eating_out', 'eating_out')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateField(),
        ),
    ]
