# Generated by Django 3.0.2 on 2020-04-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0002_auto_20200221_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tag',
            field=models.CharField(choices=[('cloths', 'cloths'), ('coffie', 'coffie'), ('same', 'same'), ('other', 'other'), ('outings', 'outings'), ('supermarcket', 'supermarcket'), ('transportation', 'transportation'), ('eating_out', 'eating_out'), ('bills', 'bills'), ('home', 'home')], default=1, max_length=50),
        ),
    ]
