# Generated by Django 3.0.2 on 2020-04-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0004_transaction_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('file_name', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
