# Generated by Django 3.0.2 on 2020-04-12 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0006_auto_20200412_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tag',
            field=models.CharField(max_length=50),
        ),
    ]
