# Generated by Django 3.0.2 on 2020-04-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0009_dateinput'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='month_date',
            field=models.DateField(null=True),
        ),
    ]
