# Generated by Django 3.2.14 on 2022-07-21 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myFinance', '0019_tag_expense'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGoal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myFinance.tag')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
