# Generated by Django 3.2.14 on 2022-08-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0023_remove_transaction_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='tag_ref',
            new_name='tag',
        ),
    ]
