# Generated by Django 3.2.14 on 2022-09-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0026_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='company',
            field=models.CharField(choices=[('Discount', 'Discount'), ('Cal', 'Cal'), ('Visa', 'Visa')], default='1', max_length=30),
        ),
    ]
