# Generated by Django 3.2.14 on 2022-09-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0028_alter_credential_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='last_scanned',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='credential',
            name='company',
            field=models.CharField(choices=[('DISCOUNT', 'Discount'), ('CAL', 'Cal'), ('MAX', 'Max')], default='1', max_length=30),
        ),
    ]
