# Generated by Django 3.2.14 on 2022-10-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0032_credential_additional_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('MONTHLY_FIXED', 'MONTHLY FIXED'), ('PERIODIC', 'PERIODIC'), ('CONTINUOUS', 'CONTINUOUS')], default='1', max_length=32),
        ),
    ]
