# Generated by Django 3.2.14 on 2023-01-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0038_errorlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='type',
            field=models.CharField(choices=[('MONTHLY FIXED', 'MONTHLY FIXED'), ('PERIODIC', 'PERIODIC'), ('CONTINUOUS', 'CONTINUOUS')], default='1', max_length=32),
        ),
    ]
