# Generated by Django 3.2.14 on 2025-01-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0040_auto_20250122_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='credential',
        ),
    ]
