# Generated by Django 3.2.14 on 2025-01-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0041_remove_credential_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='credential',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
