# Generated by Django 3.0.2 on 2020-04-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0003_auto_20200404_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='month',
            field=models.IntegerField(null=True),
        ),
    ]
