# Generated by Django 3.0.2 on 2020-04-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0005_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='file_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
