# Generated by Django 3.0.2 on 2020-04-13 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0007_auto_20200412_0325'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tag_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myFinance.Tag'),
        ),
    ]
