# Generated by Django 3.0.2 on 2020-04-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0008_transaction_tag_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateField()),
            ],
        ),
    ]
