# Generated by Django 2.1.7 on 2020-05-05 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0011_auto_20200505_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dateinput',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
