# Generated by Django 2.1.7 on 2020-05-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0015_tag_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank',
            field=models.BooleanField(default=False),
        ),
    ]
