# Generated by Django 2.1.7 on 2020-06-19 13:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myFinance', '0016_transaction_bank'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionnametag',
            unique_together={('user', 'transaction_name')},
        ),
    ]
