# Generated by Django 3.0.8 on 2020-08-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0018_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='expense',
            field=models.BooleanField(default=False),
        ),
    ]
