# Generated by Django 3.2.14 on 2022-08-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0021_auto_20220810_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='file_name',
        ),
    ]
