# Generated by Django 3.2.14 on 2022-08-22 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0022_remove_tag_file_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='tag',
        ),
    ]
