# Generated by Django 3.2.14 on 2022-09-05 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_kms.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myFinance', '0024_rename_tag_ref_transaction_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', django_kms.fields.KMSEncryptedCharField(editable=True, key_id='7388ca30-4279-45cc-a05e-f05f9fb7d4af')),
                ('user_identification', django_kms.fields.KMSEncryptedCharField(editable=True, key_id='7388ca30-4279-45cc-a05e-f05f9fb7d4af')),
                ('user_name', django_kms.fields.KMSEncryptedCharField(editable=True, key_id='7388ca30-4279-45cc-a05e-f05f9fb7d4af')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
