# Generated by Django 3.2.14 on 2022-09-21 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0027_credential_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='company',
            field=models.CharField(choices=[('DISCOUNT', 'Discount'), ('CAL', 'Cal'), ('VISA', 'Visa')], default='1', max_length=30),
        ),
    ]
