# Generated by Django 3.2.14 on 2022-09-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0029_auto_20220921_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='key',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
