# Generated by Django 3.2.14 on 2022-09-27 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0030_tag_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='type',
            field=models.CharField(choices=[('BANK', 'Bank'), ('DEBIT_CARD', 'Debit Card')], default='1', max_length=32),
        ),
    ]
