# Generated by Django 3.2.14 on 2022-09-27 21:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0031_credential_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='additional_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
