# Generated by Django 3.2.14 on 2022-10-16 08:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0034_transaction_credential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
