# Generated by Django 3.2.14 on 2025-01-22 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myFinance', '0039_alter_tag_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='arn',
        ),
        migrations.AddField(
            model_name='transaction',
            name='credential',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myFinance.credential'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='identifier',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
